//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject_StudentPlacement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GHTPlacement : DbContext
    {
        public GHTPlacement()
            : base("name=GHTPlacement")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCours> tblCourses { get; set; }
        public virtual DbSet<tblCSJoin> tblCSJoins { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
        public virtual DbSet<tblPlacement> tblPlacements { get; set; }
        public virtual DbSet<tblRoleMgt> tblRoleMgts { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblStudent> tblStudents { get; set; }
    }
}
