//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject_StudentPlacement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCSJoin
    {
        public int id { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> placementID { get; set; }
    
        public virtual tblCours tblCours { get; set; }
        public virtual tblPlacement tblPlacement { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
