//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject_StudentPlacement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCours()
        {
            this.tblCSJoins = new HashSet<tblCSJoin>();
        }
    
        public int crId { get; set; }
        public string Course_name { get; set; }
        public int fees { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCSJoin> tblCSJoins { get; set; }
    }
}
